# Generated by Django 4.2.11 on 2025-09-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.TextField(blank=True, verbose_name="file_path"),
        ),
    ]
