# Generated by Django 4.2.11 on 2025-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_filmwork_film_work_creation_date_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("genre", "film_work"), name="uk_genre_film"
            ),
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("person", "film_work", "role"), name="uq_person_film_role"
            ),
        ),
    ]
