# Generated by Django 4.2.11 on 2025-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_genrefilmwork_uk_genre_film_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmwork",
            options={
                "ordering": ["-title"],
                "verbose_name": "Кинопроизведение",
                "verbose_name_plural": "Кинопроизведения",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["-name"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["-full_name"],
                "verbose_name": "Персона",
                "verbose_name_plural": "Персоны",
            },
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="person",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="person",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
    ]
